# Generated by Django 4.1.7 on 2023-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=None, max_length=50)),
                ('type', models.CharField(choices=[('breakfast', 'Breakfast'), ('second_breakfast', 'Second Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('supper', 'Supper'), ('misc', 'Misc')], max_length=50)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('meat', 'Meat'), ('dairy', 'Dairy'), ('eggs', 'Eggs'), ('fruits', 'Fruits'), ('vegetables', 'Vegetables'), ('pasta', 'Pasta/Grains'), ('drinks', 'Drinks'), ('fats', 'Fats'), ('breadstuff', 'Breadstuff'), ('nuts', 'Nuts'), ('fish', 'Fish'), ('mushrooms', 'Mushrooms'), ('misc', 'Misc')], max_length=50)),
                ('proteins', models.FloatField(verbose_name='Proteins per 100g')),
                ('carbs', models.FloatField(verbose_name='Carbs per 100g')),
                ('fats', models.FloatField(verbose_name='Fats per 100g')),
                ('kcal', models.FloatField(verbose_name='Kcal per 100g')),
            ],
        ),
    ]
