# Generated by Django 4.1.7 on 2023-05-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_alter_meal_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='day',
            new_name='meal_day',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='type',
            new_name='meal_type',
        ),
    ]
