# Generated by Django 4.1.7 on 2023-04-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Untitled', max_length=255)),
                ('content', models.TextField(blank=True, default='No content')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
